// Copyright (c) 2026 Massimo Federico Bonfigli
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// cpporacle_test.go — table-driven tests against fixtures generated by the
// LASzip C++ reference implementation (scripts/fixturegen, pinned to
// upstream ac3e9e9). The CSVs were produced by the C++ LASunzipper decode
// and oracle.json records the C++ reader's observed behavior on corrupt
// files; both are the ground truth here.
package laz

import (
	"encoding/binary"
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"
)

// ---------------------------------------------------------------------------
// Multichannel LAS 1.4 fixtures — POINT14 v3/v4 with 160 scanner-channel
// switches (127 to already-used channels within a chunk). These exercise the
// v3 context-propagation semantics that single-channel files never touch.
// ---------------------------------------------------------------------------

func TestCPPOracleMultichannel(t *testing.T) {
	dir := filepath.Join("testdata", "cpporacle")
	tests := []struct {
		name   string
		base   string
		hasNIR bool
		hasEB  bool // GridID uint32 + Confidence float32 extra bytes
	}{
		{"pf7 v3 RGB14", "las14_pf7_v3_multichannel_1000pts", false, false},
		{"pf8 v4 RGBNIR14 with extra bytes", "las14_pf8_v4_multichannel_1000pts", true, true},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			ref := parseRefCSV(t, filepath.Join(dir, tc.base+".csv"))

			lasPts, uLas := readAll(t, filepath.Join(dir, tc.base+".las"))
			defer uLas.Close()
			lazPts, uLaz := readAll(t, filepath.Join(dir, tc.base+".laz"))
			defer uLaz.Close()

			if len(lazPts) != len(ref) || len(lasPts) != len(ref) {
				t.Fatalf("point counts: laz=%d las=%d csv=%d", len(lazPts), len(lasPts), len(ref))
			}

			// 1. Decompressed records must match the raw records byte-for-byte.
			for pi := range lazPts {
				lb, sb := lazPts[pi].buf, lasPts[pi].buf
				for i := range lb {
					if lb[i] != sb[i] {
						t.Fatalf("pt %d byte %d: laz=%02x las=%02x", pi, i, lb[i], sb[i])
					}
				}
			}

			// 2. Field-level check against the C++-decoded CSV.
			sx, sy, sz, _, _, _ := uLaz.Scale()
			items := uLaz.Items()
			offsets := uLaz.Offsets()
			for pi, r := range ref {
				b := lazPts[pi].buf

				x := float64(int32(binary.LittleEndian.Uint32(b[0:4]))) * sx
				y := float64(int32(binary.LittleEndian.Uint32(b[4:8]))) * sy
				z := float64(int32(binary.LittleEndian.Uint32(b[8:12]))) * sz
				if !within(x, r.X, 1e-9) || !within(y, r.Y, 1e-9) || !within(z, r.Z, 1e-9) {
					t.Fatalf("pt %d coords: (%v,%v,%v) != csv (%v,%v,%v)", pi, x, y, z, r.X, r.Y, r.Z)
				}
				if got := binary.LittleEndian.Uint16(b[12:14]); got != r.Intensity {
					t.Errorf("pt %d intensity: %d != %d", pi, got, r.Intensity)
				}
				if got := b[24] & 0x0F; got != r.ReturnNumber {
					t.Errorf("pt %d return number: %d != %d", pi, got, r.ReturnNumber)
				}
				if got := (b[24] >> 4) & 0x0F; got != r.NumberOfReturns {
					t.Errorf("pt %d number of returns: %d != %d", pi, got, r.NumberOfReturns)
				}
				if got := p14Class(b); got != r.Classification {
					t.Errorf("pt %d classification: %d != %d", pi, got, r.Classification)
				}
				if got := p14UserData(b); got != r.UserData {
					t.Errorf("pt %d user data: %d != %d", pi, got, r.UserData)
				}
				if got := p14PointSourceID(b); got != r.PointSourceID {
					t.Errorf("pt %d point source: %d != %d", pi, got, r.PointSourceID)
				}
				if got := p14ScanAngle(b); got != r.ScanAngle {
					t.Errorf("pt %d scan angle: %d != %d", pi, got, r.ScanAngle)
				}
				if got := p14GPS(b); !within(got, r.GPSTime, 1e-6) {
					t.Errorf("pt %d gps: %v != %v", pi, got, r.GPSTime)
				}

				// RGB lives in the second item (RGB14 or RGBNIR14).
				ro := offsets[1]
				if got := binary.LittleEndian.Uint16(b[ro : ro+2]); got != r.Red {
					t.Errorf("pt %d red: %d != %d", pi, got, r.Red)
				}
				if got := binary.LittleEndian.Uint16(b[ro+2 : ro+4]); got != r.Green {
					t.Errorf("pt %d green: %d != %d", pi, got, r.Green)
				}
				if got := binary.LittleEndian.Uint16(b[ro+4 : ro+6]); got != r.Blue {
					t.Errorf("pt %d blue: %d != %d", pi, got, r.Blue)
				}
				if tc.hasNIR {
					if got := binary.LittleEndian.Uint16(b[ro+6 : ro+8]); got != r.NIR {
						t.Errorf("pt %d nir: %d != %d", pi, got, r.NIR)
					}
				}
				if tc.hasEB {
					eo := offsets[2]
					if got := binary.LittleEndian.Uint32(b[eo : eo+4]); got != r.GridID {
						t.Errorf("pt %d GridID: %d != %d", pi, got, r.GridID)
					}
					if got := math.Float32frombits(binary.LittleEndian.Uint32(b[eo+4 : eo+8])); got != r.Confidence {
						t.Errorf("pt %d Confidence: %v != %v", pi, got, r.Confidence)
					}
				}
				if len(items) == 0 {
					t.Fatal("no items")
				}
			}
		})
	}
}

// ---------------------------------------------------------------------------
// Corrupt chunk-table fixtures — expected behavior recorded from the C++
// reader in oracle.json: recovery to sequential reading for corrupt table
// offsets (all 1000 points decode, warning only), and a clean error after
// the last intact chunk of a truncated file.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Mid-chunk corruption salvage — oracle_salvage.json records the C++ reader's
// per-read behavior over a file whose chunk 3 has a corrupted arithmetic
// seed: one failing read, then recovery at the next tabled chunk.
// ---------------------------------------------------------------------------

type salvageSegment struct {
	ReadsFrom    *int    `json:"reads_from"`
	ReadsTo      *int    `json:"reads_to"`
	PristineFrom *int    `json:"pristine_from"`
	ErrorAtRead  *int    `json:"error_at_read"`
	Error        *string `json:"error"`
	Failed       bool    `json:"failed"`
	Garbage      bool    `json:"garbage"`
}

type salvageOracle struct {
	Segments []salvageSegment `json:"segments"`
}

func TestCPPOracleSalvage(t *testing.T) {
	dir := filepath.Join("testdata", "cpporacle", "corrupt")
	raw, err := os.ReadFile(filepath.Join(dir, "oracle_salvage.json"))
	if err != nil {
		t.Fatalf("read oracle_salvage.json: %v", err)
	}
	var oracle map[string]salvageOracle
	if err := json.Unmarshal(raw, &oracle); err != nil {
		t.Fatalf("parse oracle_salvage.json: %v", err)
	}

	pristine, uP := readAll(t, filepath.Join("testdata", "las", "las12_pf3_1000pts_with_extrabytes.las"))
	uP.Close()

	for name, want := range oracle {
		t.Run(name, func(t *testing.T) {
			u, err := OpenLAS(filepath.Join(dir, name))
			if err != nil {
				t.Fatalf("OpenLAS: %v", err)
			}
			defer u.Close()

			items := u.Items()
			offsets := u.Offsets()
			buf := make([]byte, offsets[len(offsets)-1])
			pt := make([][]byte, len(items))
			for j := range items {
				pt[j] = buf[offsets[j]:offsets[j+1]]
			}

			read := func(i int) error {
				t.Helper()
				return u.Read(pt)
			}

			for _, seg := range want.Segments {
				switch {
				case seg.ErrorAtRead != nil:
					i := *seg.ErrorAtRead
					if err := read(i); err == nil {
						t.Fatalf("read %d succeeded; C++ failed with %q", i, *seg.Error)
					}
					if seg.Error != nil && u.reader.Error() != *seg.Error {
						t.Errorf("read %d error mismatch:\n  go : %q\n  c++: %q", i, u.reader.Error(), *seg.Error)
					}
				case seg.Failed:
					for i := *seg.ReadsFrom; i <= *seg.ReadsTo; i++ {
						if err := read(i); err == nil {
							t.Fatalf("read %d succeeded; C++ oracle marks reads %d-%d failed", i, *seg.ReadsFrom, *seg.ReadsTo)
						}
					}
					if seg.Error != nil && u.reader.Error() != *seg.Error {
						t.Errorf("failed-run error mismatch:\n  go : %q\n  c++: %q", u.reader.Error(), *seg.Error)
					}
				default:
					for i := *seg.ReadsFrom; i <= *seg.ReadsTo; i++ {
						if err := read(i); err != nil {
							t.Fatalf("read %d: %v (C++ oracle decodes it)", i, err)
						}
						if seg.Garbage {
							continue
						}
						pi := *seg.PristineFrom + (i - *seg.ReadsFrom)
						pb := pristine[pi].buf
						for k := range buf {
							if buf[k] != pb[k] {
								t.Fatalf("read %d byte %d: got %02x, pristine[%d] has %02x", i, k, buf[k], pi, pb[k])
							}
						}
					}
				}
			}
		})
	}
}

type corruptOracle struct {
	OpenOK     bool    `json:"open_ok"`
	PointsOK   uint32  `json:"points_ok"`
	ErrorAt    *int    `json:"error_at"`
	MatchesLas bool    `json:"matches_las"`
	Error      *string `json:"error"`
	Warning    string  `json:"warning"`
}

func TestCPPOracleCorruptChunkTables(t *testing.T) {
	dir := filepath.Join("testdata", "cpporacle", "corrupt")

	raw, err := os.ReadFile(filepath.Join(dir, "oracle.json"))
	if err != nil {
		t.Fatalf("read oracle.json: %v", err)
	}
	var oracle map[string]corruptOracle
	if err := json.Unmarshal(raw, &oracle); err != nil {
		t.Fatalf("parse oracle.json: %v", err)
	}
	if len(oracle) == 0 {
		t.Fatal("oracle.json is empty")
	}

	// Pristine counterpart: the corrupt fixtures derive from this file.
	pristine, uP := readAll(t, filepath.Join("testdata", "las", "las12_pf3_1000pts_with_extrabytes.las"))
	uP.Close()

	for name, want := range oracle {
		t.Run(name, func(t *testing.T) {
			u, err := OpenLAS(filepath.Join(dir, name))
			if !want.OpenOK {
				if err == nil {
					u.Close()
					t.Fatal("OpenLAS succeeded, C++ oracle failed at open")
				}
				return
			}
			if err != nil {
				t.Fatalf("OpenLAS: %v (C++ opens this file)", err)
			}
			defer u.Close()

			items := u.Items()
			offsets := u.Offsets()
			buf := make([]byte, offsets[len(offsets)-1])
			pt := make([][]byte, len(items))
			for j := range items {
				pt[j] = buf[offsets[j]:offsets[j+1]]
			}

			var decoded uint32
			var readErr error
			for i := uint32(0); i < u.NumPoints(); i++ {
				if readErr = u.Read(pt); readErr != nil {
					break
				}
				// Verify against the pristine record, like the C++ harness did.
				if want.MatchesLas && decoded < uint32(len(pristine)) {
					pb := pristine[decoded].buf
					for k := range buf {
						if buf[k] != pb[k] {
							t.Fatalf("pt %d byte %d: got %02x, pristine %02x", decoded, k, buf[k], pb[k])
						}
					}
				}
				decoded++
			}

			if decoded != want.PointsOK {
				t.Errorf("decoded %d points, C++ oracle decoded %d (last err: %v)", decoded, want.PointsOK, readErr)
			}
			if want.ErrorAt != nil {
				if readErr == nil {
					t.Errorf("expected a read error at point %d like C++, got none", *want.ErrorAt)
				}
				if want.Error != nil && u.reader.Error() != *want.Error {
					t.Errorf("error string mismatch:\n  go : %q\n  c++: %q", u.reader.Error(), *want.Error)
				}
			} else if readErr != nil {
				t.Errorf("unexpected read error: %v (C++ decodes all points)", readErr)
			}
			if want.Warning != "" && u.reader.Warning() != want.Warning {
				t.Errorf("warning mismatch:\n  go : %q\n  c++: %q", u.reader.Warning(), want.Warning)
			}
		})
	}
}
